apiVersion: v1
kind: Namespace
metadata:
  name: kube-network-watcher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: kube-network-watcher
spec:
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - image: pskreter/kube-network-watcher:v0.0.2-alpha
        name: controller
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
