apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - name: controller
          image: pskreter/kube-network-watcher:latest
          command:
            - "/kube-network-watcher"
            - "controller"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP