apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-network-watcher

resources:
- namespace.yaml
- deployment.yaml

images:
- name: controller
  newName: pskreter/kube-network-watcher
  newTag: v0.0.3-alpha
- name: pskreter/kube-network-watcher
  newTag: v0.0.1-alpha
